config/routes.rb
QuanduOmeka::Application.routes.draw do

  get 'instances/thanks'

  resources :instances, only: [:new, :create]

  namespace :admin do
    resources :instances
  end

  root :to => 'instances#new'

end

app/models/instance.rb
class Instance < ActiveRecord::Base

  #validates :course, :presence => true
  #validates :instructor, :presence => true
  #validates :terms, :acceptance => true

  validates :course, :presence => true, :length => { :maximum => 50 }
  #validates :instructor, :presence => true, :length => { :maximum => 50 }
  validates :terms, :acceptance => {:accept => true }

  validates_uniqueness_of :course

  attr_accessible :course, :instructor, :terms

end

app/controllers/admin/instances_controller.rb
class Admin::InstancesController < ApplicationController

  # GET /instances
  def index
    @instances = Instance.paginate(:page => params[:page])
  end

  # GET /instances/1
  def show
    @instance = Instance.find(params[:id])
  end

  # GET /instances/new
  def new
    @instance = Instance.new
  end

  # GET /instances/1/edit
  def edit
    @instance = Instance.find(params[:id])
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(params[:instance])

    respond_to do |format|
      if @instance.save
        #format.html { redirect_to @instance, notice: 'Request was made.' }
        format.html { redirect_to admin_instances_path, notice: 'Request was made.' }
      else
        format.html { render action: "new" }
      end
    end
  end

 # GET /instances/new
  def thanks
    
  end

  # PUT /instances/1
  # PUT /instances/1.json
  def update
    @instance = Instance.find(params[:id])

    respond_to do |format|
      if @instance.update_attributes(params[:instance])
        format.html { redirect_to [:admin, @instance], notice: 'Instance was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance = Instance.find(params[:id])
    @instance.destroy

    respond_to do |format|
      format.html { redirect_to instances_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController

  # GET /instances/new
  def new
    @instance = Instance.new
  end


  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(params[:instance])

    respond_to do |format|
      if @instance.save
        #format.html { redirect_to @instance, notice: 'Request was made.' }
        format.html { redirect_to instances_thanks_path, notice: 'Request was made.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # GET /instances/new
  def thanks

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
    #{messages}
    </div>
    HTML
    html.html_safe
  end


  # Based on https://gist.github.com/1182136
  # pulled from https://gist.github.com/purcell/1205828
  class BootstrapLinkRenderer < ::WillPaginate::ActionView::LinkRenderer
    protected

    def html_container(html)
      tag :div, tag(:ul, html), container_attributes
    end

    def page_number(page)
      tag :li, link(page, page, :rel => rel_value(page)), :class => ('active' if page == current_page)
    end

    def gap
      tag :li, link(super, '#'), :class => 'disabled'
    end

    def previous_or_next_page(page, text, classname)
      tag :li, link(text, page || '#'), :class => [classname[0..3], classname, ('disabled' unless page)].join(' ')
    end
  end

  def page_navigation_links(pages)
    will_paginate(pages, :class => 'pagination', :inner_window => 2, :outer_window => 0, :renderer => BootstrapLinkRenderer, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe)
  end

end

app/helpers/instances_helper.rb
module InstancesHelper

  def capistrano_config
     <<-CAPCONFIG
    <pre>
load 'recipes/cleanup.rb'

set :project_roles, %w(app db web)

set :application, "#{ @instance.course.slugify }"

load 'recipes/omeka_defaults.rb'
    </pre>

    CAPCONFIG

  end

  def apache_config(stage)
    html = <<-HTTPDCONFIG
      <pre>
&lt;VirtualHost *:80>
    DocumentRoot /usr/local/projects/#{ @instance.course.slugify }/current

    ServerName #{stage}.#{ @instance.course.slugify }.#{ENV['domain'] || 'localhost' }
    ServerAlias #{stage}.#{ @instance.course.slugify }.#{ENV['domain'] || 'localhost' }

    ErrorLog logs/#{ @instance.course.slugify }.omeka-error_log
    CustomLog logs/#{ @instance.course.slugify }.omeka-access_log common

    &lt;Directory "/usr/local/projects/#{ @instance.course.slugify }/current">
      Options FollowSymlinks
      AllowOverride All
      Order allow,deny
      Allow from all
    &lt;/Directory>


&lt;/VirtualHost>
      </pre>

    HTTPDCONFIG
    html
  end

  def db_config(stage)
    html = <<-DBCONFIG
      <pre>
[database]
host     = "#{ ENV['db_host'] ||= 'localhost' }"
username = "#{ ENV['db_user'] ||= 'username' }"
password = "#{ ENV['db_password'] ||= 'password' }"
name     = "omeka_#{ stage }"
prefix   = "#{ @instance.course.slugify }_"
;port     = ""
      </pre>
    DBCONFIG
    html
  end

end

app/views/admin/instances/_form.html.erb
<%= simple_form_for([:admin, @instance], :html => {:class => 'form-horizontal' }) do |form| %>
  <% if @instance.errors.any? %>

    <%= display_base_errors @instance %>

    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><strong>Oh snap!</strong> looks like something is wrong:</p>
      <ul>
        <% @instance.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :course, required: true, label: 'Course Number', placeholder: 'Course this will be used in' %>
  <%= form.input :instructor, label: 'Instructor', placeholder: 'Instructor of record' %>

  <h3>Terms</h3>

  <div class="well">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= form.input :terms, label: "Yes, I agree" %>
      <%= form.submit 'Make your request', :class => "btn btn-large btn-success"%>
    </div>
  </div>
<% end %>

app/views/admin/instances/edit.html.erb
<h1>Editing instance</h1>

<%= render 'form' %>

app/views/admin/instances/index.html.erb
<h1>Neatline Instances <%= link_to 'New Instance', new_admin_instance_path, :class => 'btn btn-primary' %></h1>

<%= page_navigation_links @instances %>

<table class="table table-striped">
  <tr>
    <th>Course</th>
    <th>Instructor</th>
    <th>Terms</th>
    <th></th>
    <th></th>
  </tr>

<% @instances.each do |instance| %>
  <tr>
    <td><%= link_to instance.course, admin_instance_path(instance) %></td>
    <td><%= instance.instructor %></td>
    <td><% if instance.terms %><i class="icon-ok"></i><% end %></td>
    <td><%= link_to 'Edit', edit_admin_instance_path(instance), :class => 'btn btn-info' %></td>
    <td><%= link_to 'Delete', [:admin, instance], :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/admin/instances/new.html.erb
<h1>Request a Neatline Instance</h1>

<p class="lead">
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<%= render 'form' %>

app/views/admin/instances/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Neatline Instances', admin_instances_path %> <span class="divider">/</span></li>
  <li class="active"><%= @instance.course.titleize %></li>
</ul>

<div class="hero-unit">
  <div class="page-header">
    <h1>Course <small><%= @instance.course %></small></h1>
  </div>

  <p>
    <strong>Instructor:</strong>
    <%= @instance.instructor %>
  </p>

  <%= link_to 'Edit', edit_admin_instance_path(@instance), :class => 'btn btn-primary btn-large' %> 
</div>

<div id="apache" class="row">
  <h1>Apache Config</h1>
  <div class="span6">
    <h2>Staging</h2>
    <%= apache_config('staging').html_safe %>
  </div>
  <div class="span6">
    <h2>Production</h2>
    <%= apache_config('production').html_safe %>
  </div>
</div>

<div id="capistrano" class="row">
  <h1>Capistrano</h1>
  <div class="span12">
    <%= capistrano_config.html_safe %>
  </div>
</div>

<div id="omeka_db" class="row">
  <h1>Database config</h1>
  <div class="span6">
    <h2>Staging</h2>
    <%= db_config('staging').html_safe %>
  </div>
  <div class="span6">
    <h2>Production</h2>
    <%= db_config('production').html_safe %>
  </div>
</div>

app/views/admin/instances/thanks.html.erb
<div class="jumbotron">
  <h1>Thanks</h1>
  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p class="pull-right">&mdash;Scholars' Lab</p>
</div>

app/views/instances/_form.html.erb
  <%= simple_form_for(@instance, :html => {:class => 'form-horizontal' }) do |form| %>
    <% if @instance.errors.any? %>

      <%= display_base_errors @instance %>

      <div class="alert alert-error alert-block">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><strong>Oh snap!</strong> looks like something is wrong:</p>
        <ul>
        <% @instance.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
      </div>
    <% end %>

  <%= form.input :course, required: true, label: 'Course Number', placeholder: 'Course this will be used in' %>
  <%= form.input :instructor, label: 'Instructor', placeholder: 'Instructor of record' %>
  <h3>Terms</h3>

  <div class="well">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= form.input :terms, label: "Yes, I agree" %>
      <%= form.submit 'Make your request', :class => "btn btn-large btn-success"%>
    </div>
  </div>
<% end %>

app/views/instances/edit.html.erb
<h1>Editing instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance %> |
<%= link_to 'Back', instances_path %>

app/views/instances/index.html.erb
<h1>Listing instances <%= link_to 'New Instance', new_instance_path, :class => 'btn btn-primary' %></h1>

<p></p>

<table class="table table-striped">
  <tr>
    <th>Course</th>
    <th>Instructor</th>
    <th>Terms</th>
    <th></th>
    <th></th>
  </tr>

<% @instances.each do |instance| %>
  <tr>
    <td><%= link_to instance.course, instance %></td>
    <td><%= instance.instructor %></td>
    <td><% if instance.terms %><i class="icon-ok"></i><% end %></td>
    <td><%= link_to 'Edit', edit_instance_path(instance), :class => 'btn btn-info' %></td>
    <td><%= link_to 'Delete', instance, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/instances/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Back', instances_path %> <span class="divider">/</span></li>
  <li class="active"><%= @instance.course.titleize %></li>
</ul>

<p id="notice"><%= notice %></p>

<div class="hero-unit">
 
  <div class="page-header">
  <h1>Course <small><%= @instance.course %></small></h1>
</div>
  
<p>
  <strong>Instructor:</strong>
  <%= @instance.instructor %>
  </p>
<%= link_to 'Edit', edit_instance_path(@instance), :class => 'btn btn-primary btn-large' %> 

 
</div>


  <div id="apache" class="row">
    <h1>Apache Config</h1>

    <div class="span6">
    <h2>Staging</h2>
    <pre>
  &lt;VirtualHost *:80>
     DocumentRoot /usr/local/projects/<%= @instance.course.downcase %>/current

     ServerName  staging.<%= @instance.course.downcase %>.lib.virginia.edu
     ServerAlias staging.<%= @instance.course.downcase %>.lib.virginia.edu

     ErrorLog  logs/<%= @instance.course.downcase %>.omeka-error_log
     CustomLog logs/<%= @instance.course.downcase %>.omeka-access_log common

     &lt;Directory "/usr/local/projects/<%= @instance.course.downcase %>/current">
        Options FollowSymlinks
        AllowOverride All
        Order allow,deny
        Allow from all
     &lt;/Directory>

  &lt;/VirtualHost>
    </pre>
  </div>

      <div class="span6">
      <h2>Production</h2>
    <pre>
  &lt;VirtualHost *:80>
     DocumentRoot /usr/local/projects/<%= @instance.course.downcase %>/current

     ServerName  <%= @instance.course.downcase %>.lib.virginia.edu
     ServerAlias <%= @instance.course.downcase %>.lib.virginia.edu

     ErrorLog  logs/<%= @instance.course.downcase %>.omeka-error_log
     CustomLog logs/<%= @instance.course.downcase %>.omeka-access_log common

     &lt;Directory "/usr/local/projects/<%= @instance.course.downcase %>/current">
        Options FollowSymlinks
        AllowOverride All
        Order allow,deny
        Allow from all
     &lt;/Directory>

  &lt;/VirtualHost>
    </pre>
  </div>
  </div>

  <div id="capistrano" class="row">
     <h1>Capistrano</h1>

    <div class="span12">
    <pre>
load 'recipes/cleanup.rb'

set :project_roles, %w(app db web)

set :application, "<%= @instance.course.downcase %>"

load 'recipes/omeka_defaults.rb'
    </pre>
  </div>
  </div>

  <div id="omeka_db" class="row">
    <h1>Database config</h1>
    <div class="span6">

    <h2>Staging</h2>
  <pre>
[database]
host     = "sds2.itc.virginia.edu"
username = "omeka_user"
password = "123456"
name     = "omeka_staging"
prefix   = "<%= @instance.course.downcase %>_"
;port     = ""
  </pre>
</div>
<div class="span6">
<h2>Production</h2>

    <pre>
[database]
host     = "sds2.itc.virginia.edu"
username = "omeka_user"
password = "123456"
name     = "omeka_production"
prefix   = "<%= @instance.course.downcase %>_"
;port     = ""
  </pre>
</div>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Neatline Instance Request" %></title>
<meta name="description" content="">
<meta name="author" content="">
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= yield(:head) %>
</head>
<body>
<header class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <div class="container">
      <%= link_to "Neatline Request", root_path, :class => 'brand' %>
      <ul class="nav">
        <li>&nbsp;</li>
      </ul>
    </ul>
  </div>
</nav>
</header>
<div role="main" class="container">
<div class="row">
  <div class="span12">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</div>
<hr/>
<footer class="row">
  <div class="vcard span6" id="slab-vcard">
    <address>
      <%= link_to("Scholars’ Lab", 'http://scholarslab.org')%><br/>
      <%= link_to('University of Virginia Library', 'http://library.virginia.edu')%><br/>
      P.O. Box 400129<br/>
      Charlottesville, VA 22904-4129<br/>
      <abbr title="Phone">T:</abbr> 434.243.8800<br/>
      <abbr title="fax">F:</abbr> 434.924.1431
    </address>
  </div>

  <div id="social-media" class="span6 omega">
    <p><strong>Find Scholars’ Lab Elsewhere</strong></p>
    <a href="http://twitter.com/scholarslab"><img src="http://www.scholarslab.org/wp-content/themes/labnotes/images/xtwitter.png.pagespeed.ic.SShtyeRWcL.png"></a>
    <a href="https://www.facebook.com/scholarslab"><img src="http://www.scholarslab.org/wp-content/themes/labnotes/images/xfacebook.png.pagespeed.ic.-Mn9k5pNqG.png"></a>
    <a href="https://plus.google.com/114472010795641313811"><img src="http://www.scholarslab.org/wp-content/themes/labnotes/images/xgoogleplus.png.pagespeed.ic.e_aeZtD88c.png"></a>
    <a href="https://vimeo.com/scholarslab"><img src="http://www.scholarslab.org/wp-content/themes/labnotes/images/xvimeo.png.pagespeed.ic.S9LZcs5YOj.png"></a>
    <a href="http://github.com/scholarslab/"><img src="http://www.scholarslab.org/wp-content/themes/labnotes/images/xgithub.png.pagespeed.ic.avX8Ahk6_q.png"></a>
  </div>
</footer>
</div> <!--! end of #main -->
</body>
</html>